version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Add additional services here if needed
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"